package com.ibm.training.basics;
//package com.ibm.training; // packages all in lower case

public class JavaNamingConventions { // Class/type names begin with upper case, every word starts in upper case. use
										// nouns
	
	final int MIN_AGE = 18; //all caps for constants
	
	int age; // var names begin with lower case
	String firstName; // notice camel casing

	public void read() { // method names also begin with lower case. use verbs

	}

	public void readFile(String fileName) { // method names also begin with lower case. notice camel casing

	}
	
	//----------- spl
	// A$B -------> class B is an inner class of A
	
	int _height = 20; //vars and methods beginning with _ ==> generated by some code generator
	public void _uiSetUp() {
		
	}
}
